schema_version = "1.0.0"

id = "multi_adjust"
version = "1.0.0"
name = "Multi Adjust"
tagline = "Edits properties of multiple things together"
maintainer = "Brrainz <andreas@pardeike.net>"
type = "add-on"

tags = ["Modeling"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

copyright = [
  "2025 Andreas Pardeike",
]